include:
  - project: openresearch/gitlab-build-templates
    ref: main
    file:
      - '/.gitlab-cicd-shared.yml'
      - '/.gitlab-cicd-java21.yml'

stages:
  - Build
  - Publish

build:
  extends: .build
  artifacts:
    paths:
      - build/libs/t60f.jar
  services:
    - name: docker:dind
      # explicitly disable tls to avoid docker startup interruption
      command: [ '--tls=false' ]

gen-sbom:
  stage: Build
  image: mbopm/openjdk-alpine-jdk:jdk21
  tags:
    - docker
  services:
    - name: docker:dind
      # explicitly disable tls to avoid docker startup interruption
      command: [ '--tls=false' ]
  artifacts:
    paths:
      - build/reports/bom.json
  script:
    - ./gradlew clean cyclonedxBom

scan:
  stage: Build
  image: docker:latest
  tags:
    - docker
  services:
    - name: docker:dind
      # explicitly disable tls to avoid docker startup interruption
      command: [ '--tls=false' ]
  needs:
    - job: gen-sbom
      artifacts: true
  script:
    - docker run -it -v "${PWD}":/src ghcr.io/google/osv-scanner scan -r -S /src/build/reports/bom.json /src

publish:
  stage: Publish
  image: docker:latest
  needs:
    - job: build
      artifacts: true
  tags:
    - docker
  services:
    - name: docker:dind
      # explicitly disable tls to avoid docker startup interruption
      command: [ '--tls=false' ]
  variables:
    APP: t60f
  script:
    - docker login -u $DOCKER_LOGIN_USERNAME -p $DOCKER_LOGIN_PASSWORD
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker context create builder-context
    - docker buildx create --name builderx --use builder-context
    # --provenance false is a workaround for: https://gitlab.com/gitlab-org/gitlab/-/issues/389577
    - docker buildx build --build-arg BUILDKIT_INLINE_CACHE=1 --provenance false --push --platform linux/amd64,linux/arm64/v8 -t $CI_REGISTRY_IMAGE/${APP}:${CI_COMMIT_TAG} -f Dockerfile .
  only:
    - tags
