include:
  - project: openresearch/gitlab-build-templates
    ref: main
    file:
      - '/.gitlab-cicd-shared.yml'
      - '/.gitlab-cicd-java21.yml'

stages:
  - Build
  - Publish

variables:
  SENTRY_ENVIRONMENT: "${SENTRY_ENVIRONMENT:-production}"
  SENTRY_RELEASE: "${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"

services:
  - name: docker:dind
    # explicitly disable tls to avoid docker startup interruption
    command: [ '--tls=false' ]

build:
  extends: .build
  artifacts:
    paths:
      - build/libs/t60f.jar

gen-sbom:
  stage: Build
  image: mbopm/openjdk-alpine-jdk:jdk21
  tags:
    - docker
  artifacts:
    paths:
      - build/reports/bom.json
  script:
    - ./gradlew clean cyclonedxBom

scan:
  stage: Build
  image: docker:latest
  tags:
    - docker
  needs:
    - job: gen-sbom
      artifacts: true
  script:
    - docker run -v "${PWD}":/src ghcr.io/google/osv-scanner scan -r -S /src/build/reports/bom.json /src

publish:
  stage: Publish
  image: docker:latest
  needs:
    - job: build
      artifacts: true
  tags:
    - docker
  variables:
    APP: t60f
  script:
    - docker login -u $DOCKER_LOGIN_USERNAME -p $DOCKER_LOGIN_PASSWORD
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker context create builder-context
    - docker buildx create --name builderx --use builder-context
    # --provenance false is a workaround for: https://gitlab.com/gitlab-org/gitlab/-/issues/389577
    - docker buildx build --build-arg BUILDKIT_INLINE_CACHE=1 --provenance false --push --platform linux/amd64,linux/arm64/v8 -t $CI_REGISTRY_IMAGE/${APP}:${CI_COMMIT_TAG} -f Dockerfile .
  only:
    - tags

sentry-release:
  stage: Publish
  image: node:23-alpine
  needs:
    - job: build
  before_script:
    - npm install -g @sentry/cli
  script:
    - sentry-cli releases new "$SENTRY_RELEASE" --org dev.mbo --project t60f
    - sentry-cli releases set-commits "$SENTRY_RELEASE" --auto
    - sentry-cli releases deploys "$SENTRY_RELEASE" new -e "$SENTRY_ENVIRONMENT"
  only:
    - tags
  variables:
    SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN