services:

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: s3cr3t
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: UTC
      PGTZ: UTC
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d db" ]
      interval: 1s
      timeout: 5s
      retries: 10

  # http://smtp:pass123@127.0.0.1:8025
  # API: http://127.0.0.1:8025/api/v1/
  mail:
    image: axllent/mailpit:v1.23
    container_name: mail
    hostname: mail
    ports:
      - "127.0.0.1:1025:1025" # smtp
      - "127.0.0.1:8025:8025" # ui
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./infra/mail/auth:/auth:ro
      - mail:/data:rw
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ALLOW_INSECURE: true
      MP_UI_AUTH_FILE: /auth
      MP_SMTP_AUTH_FILE: /auth
      MP_SMTP_DISABLE_RDNS: true
      TZ: UTC
    healthcheck:
      test: wget --spider --tries 1 http://smtp:pass123@localhost:8025
      interval: 1s
      timeout: 1s
      start_interval: 1s
      retries: 5

volumes:
  db:
  mail: