logging:
  level:
    root: INFO

server:
  port: 8080
  error:
    include-exception: false
    include-message: always
    include-stacktrace: never
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health,info
      cors:
        allowed-origins: "*"
        allowed-methods: GET

spring:
  application:
    name: t60f
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 3300000
      connection-init-sql: SELECT 1
      connection-test-query: ${spring.datasource.hikari.connection-init-sql}
  flyway:
    enabled: true
  jackson:
    deserialization:
      READ_ENUMS_USING_TO_STRING: true
      FAIL_ON_UNKNOWN_PROPERTIES: false
      FAIL_ON_INVALID_SUBTYPE: false
    serialization:
      INDENT_OUTPUT: false
      ORDER_MAP_ENTRIES_BY_KEYS: true
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_EMPTY_JSON_ARRAYS: false
      WRITE_ENUMS_USING_TO_STRING: true
      WRITE_NULL_MAP_VALUES: false
      WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED: false
      FAIL_ON_SELF_REFERENCES: true
    default-property-inclusion: non_null
    time-zone: UTC
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
        generate_statistics: false
    show-sql: false
  main:
    banner-mode: off
  web:
    resources:
      add-mappings: true
  threads:
    virtual:
      enabled: true

app:
  cors:
    allowed:
      - mapping: /**
        origins:
          - "*"
        headers:
          - Origin
          - Authorization
          - Accept
          - Content-Type
          - X-Tenant-Key
          - If-None-Match
          - Cache-Control
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
          - HEAD
        exposedHeaders:
          - ETag
        maxAge: 31536000
        allowCredentials: true
